# Generated by Django 5.1.15 on 2026-05-28 19:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.RemoveField(
            model_name='obrasocial',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='obrasocial',
            name='nombre',
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='medicos_disponibles',
            field=models.ManyToManyField(related_name='obras_sociales', to='app.medico'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='name',
            field=models.CharField(default='Nombre default', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='requiereToken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='sitioWeb',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='app.especialidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='obrasocial',
            constraint=models.UniqueConstraint(fields=('name',), name='error_base_datos_obra_social_nombre_ya_existe'),
        ),
        migrations.AddConstraint(
            model_name='obrasocial',
            constraint=models.UniqueConstraint(fields=('sitioWeb',), name='error_base_datos_obra_social_sitio_web_duplicado'),
        ),
    ]
