# Generated by Django 5.2.14 on 2026-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
