# Generated by Django 5.1.15 on 2026-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ausencia_especialidad_obrasocial_paciente_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='medicos_disponibles',
            field=models.ManyToManyField(to='app.medico'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='name',
            field=models.CharField(default='Nombre default', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='requiereToken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='sitioWeb',
            field=models.URLField(blank=True),
        ),
    ]
