# Generated by Django 5.2.14 on 2026-05-23 03:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medico_matricula_alter_paciente_dni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='ausencia',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    
      
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
