# Generated by Django 5.2.15 on 2026-06-18 01:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medico_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='app.turno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
