# Generated by Django 5.2.14 on 2026-05-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ausencia_options_ausencia_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
