# Generated by Django 5.1.15 on 2026-05-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_obrasocial_medicos_disponibles_obrasocial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='sitioWeb',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
