# Generated by Django 5.2.14 on 2026-06-28 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recordatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='propuesta_creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='propuesta_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='propuesta_mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='propuesta_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
