# Generated by Django 5.1.15 on 2026-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_obrasocial_sitioweb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AddConstraint(
            model_name='obrasocial',
            constraint=models.UniqueConstraint(fields=('name',), name='error_base_datos_obra_social_nombre_ya_existe'),
        ),
        migrations.AddConstraint(
            model_name='obrasocial',
            constraint=models.UniqueConstraint(fields=('sitioWeb',), name='error_base_datos_obra_social_sitio_web_duplicado'),
        ),
    ]
