# Generated by Django 5.1.15 on 2026-05-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_obrasocial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='app.especialidad'),
        ),
    ]
