# Generated by Django 5.2.15 on 2026-06-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_turno_propuesta_creado_por_turno_propuesta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
